format = """$hostname"""
right_format = """$git_metrics$git_branch$git_status$directory$time"""

[hostname]
ssh_only = false
disabled = false
format = '[\[](fg:#FA9C1B)[$hostname]( white)[\]]( fg:#FA9C1B) '

[directory]
format = '[\[]( white)[$path](fg:#FA9C1B)[\]]( white) '
truncate_to_repo = false

[cmd_duration]
disabled = true

[git_branch]
format = '[$branch(:$remote_branch)](bold white) '

[git_metrics]
disabled = false

[line_break]
disabled = true

[time]
disabled = false
format = '[\[$time\]](fg:#fff) '
time_format = '%T'
utc_time_offset = '+2'
time_range = '00:00:00-24:00:00'

